### ISSUE TITLE
Implement API endpoint to change user's password

### ISSUE THREAD

**Issue by christophfriedrich** [SpeckiJ/UserManager#1]
- [x] That's probably one of the most common tasks, so it would be nice if we wouldn't need to delete the old user and make a new one, but be able to use this API instead :D

- [ ] Bonus points if it not only works for admins, but also without LDAP auth, via a secret token. That way users could do it themselves.

**Comment by SpeckiJ** [comment]
done in https://github.com/SpeckiJ/UserManager/commit/d54cfc2b7195f5ab6a6a4a50d788a3d053af2896

> Bonus points if it not only works for admins, but also without LDAP auth, via a secret token. That way users could do it themselves.

I don't see any way to ensure that people can only edit their own passwords. How should this "secret token" be delivered to the user? We do not record any other contact information (e.g. Email).

**Comment by christophfriedrich** [comment]
> We do not record any other contact information (e.g. Email).

But we could start doing so. Then we could create and store the secret token and email it to the also stored email address. This would enable a true "forgotten password" feature and would also allow us to create new user accounts without the user being present.

Alternatively, the token could be delivered to the user manually. That would still be more convenient than meeting the user in person so they can enter a new password.

**Comment by SpeckiJ** [comment]
original functionality was implemented in done in https://github.com/SpeckiJ/UserManager/commit/d54cfc2b7195f5ab6a6a4a50d788a3d053af2896

Migrating further discussion into https://github.com/fs-geofs/UserManager/issues/3
