### ISSUE TITLE
LDAP thinks passwords are cleartext, but they are SHA-512 hashed

### ISSUE THREAD

**Issue by christophfriedrich** [SpeckiJ/UserManager#7]
On the frontend I hash the password to SHA-512, this hash is also saved to the LDAP, but for some reason it thinks that it's a cleartext password so login won't work.

The backend should save the password with the correct type flag.

**Comment by SpeckiJ** [comment]
>  some reason it thinks that it's a cleartext password so login won't work

What Endpoint are you referring to? The API seems to correctly set the password for newly created users.

For the `/api/login` Endpoint the API needs the cleartext password. LDAP does not allow authentication using the Hash (for good reason). For a short explanation check the first Paragraph of this StackOverflow comment: https://stackoverflow.com/a/44024874

**Comment by christophfriedrich** [comment]
I'm referring to the `/users/add` endpoint.

---

**Original situation:**

When I submit a new user to the endpoint (with the password in cleartext), this is what the entry looks like in Apache Directory Studio:

![grafik](https://user-images.githubusercontent.com/17781682/49211800-ae662400-f3c0-11e8-8ce3-25241cea9d74.png)

Logging in to the wiki works, BUT:

When I doubleclick on the password, I can read the user's password in the password editor:

![grafik](https://user-images.githubusercontent.com/17781682/49211964-27fe1200-f3c1-11e8-8b3c-3acf1b01969c.png)

That's no good.

**Current situation**:

So I thought I have to SHA512-hash it before sending it and [implemented that](https://github.com/christophfriedrich/UserManager/commit/f292de3eb2de21af32e8c32acad093e8e8ad07d3#diff-528c3923d718a8860f5d8c05c3931c55R198).

Now the hash gets stored in the LDAP, BUT still with "Hash Method: Klartext". Therefore, logging in to the wiki doesn't work.

---
➡️ Stuff currently doesn't work as it should. I don't know whether the problem is on the frontend or backend, but we can't leave it as it is.

**Please reopen.**

**Comment by christophfriedrich** [comment]
I had a look at existing passwords saved with Apache Directory Studio. It seems the hashes all have the format:
> `{SHA512}` + 86 letters (both lower and upper case), slashes or pluses + `==`

I.e. they satisfy the regex: `^\{SHA512\}[A-Za-z/+]{86}==$`

The SHA512 hash I currently submit to the backend is a 128-character string in hexadecimal, i.e. `^[0-9a-f]{128}$`. So obviously it can't work.

But I don't know how I have to do it correctly, either.

**Comment by SpeckiJ** [comment]
> The SHA512 hash I currently submit to the backend is a 128-character string in hexadecimal, i.e. ^[0-9a-f]{128}$. So obviously it can't work.

yup that does not work. LDAP stores the passwords as "{<encodingtype>}<base64_password>". The backend now expects a hex encoded string and decodes it to base64 for storage.
