### ISSUE TITLE
Remove dummy password from AJAX calls

### ISSUE THREAD

**Issue by christophfriedrich** [SpeckiJ/UserManager#8]
Now that #3 is fixed, the dummy password can be removed from the frontend's AJAX calls

**Comment by christophfriedrich** [comment]
This is not implemented yet, is it? If you shuffle things around, please do so thoroughly.

**Comment by SpeckiJ** [comment]
As the API has no problem with supplying a dummy password I do not see any merit in removing it.

Keeping the dummy password might even help to mitigate further bugs by removing the edge-case of no password required on certain requests.

**Comment by christophfriedrich** [comment]
The merit would be that it's a lot cleaner. What's the point of supplying an argument that isn't needed at all. That's like calling `power(base, exponent, pi)`.

Leaving it in because that saves you work on the backend side would be a very bad practice.

And actually the password being *required* is the edge case, we only need that for addUser and none of the other requests.

**Comment by SpeckiJ** [comment]
Locking conversation as this issue is fixed now.
